<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Gatekeeper.Application\Gatekeeper.Application.csproj" />
    <ProjectReference Include="..\Gatekeeper.Infrastructure\Gatekeeper.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <PropertyGroup>
  </PropertyGroup>

</Project>
